# subscriber configuration:
#  name: source name
#  topic: topic that provides cmd_vel messages
#  timeout: time in seconds without incoming messages to consider this topic inactive
#  priority: unique unsigned integer from 0 (lowest) to MAX_INT
#  short_desc: short description (optional)

subscribers:
  - name: "keyboard steering"
    topic: "keyboard_controller"
    timeout: 0.2
    priority: 10
    short_desc: "velocity commands from a keyboard controller"
  - name: "joystick steering"
    topic: "joystick_controller"
    timeout: 1.5
    priority: 8
    short_desc: "velocity commands from a joystick controller"
  - name: "unity steering"
    topic: "unity_controller"
    timeout: 0.2
    priority: 2
    short_desc: "commands from unity program"
  - name: "command steering"
    topic: "command_controller"
    timeout: 0.2
    priority: 1
    short_desc: "commands from a process"
